In [1]:
import torch
import torch.nn as nn
import torchvision.models as models
import torch.nn.functional as F
import numpy as np
import torch.optim as optim


### 搭建模型

In [2]:
class LinearBNAC(nn.Module):
    def __init__(self, in_channels, out_channels, bias=True, dropout=0.3, is_output=False):
        super(LinearBNAC, self).__init__()
        if is_output and out_channels==1:
            self.linear = nn.Sequential(
                nn.Linear(in_channels, out_channels, bias=bias),
                nn.Sigmoid()
            )
        elif is_output:
            self.linear = nn.Sequential(
                nn.Linear(in_channels, out_channels, bias=bias),
                nn.Softmax(dim=1)
            )   
        else:
            self.linear = nn.Sequential(
                nn.Linear(in_channels, out_channels, bias=bias),
                nn.Dropout(dropout),
                nn.BatchNorm1d(out_channels),
                nn.LeakyReLU(inplace=True)
            )
            
    def forward(self, x):
        out=self.linear(x)
        return out

In [10]:
class Model(nn.Module):
    def __init__(self, input_dimention, output_classes=1):
        super(Model, self).__init__()
        self.layer1 = LinearBNAC(input_dimention, 128)
        self.layer2 = "自行定義，只要確定模型能順利運行即可，參數值沒有一定限制"
        self.layer3 = "自行定義，只要確定模型能順利運行即可，參數值沒有一定限制"
        self.output = LinearBNAC(32, output_classes, is_output=True)
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.output(x)
        return x 
        

### 準備輸入資料、優化器、標籤資料、模型輸出

In [31]:
model = Model(input_dimention=256,output_classes=10)
optimizer = "使用Adam optimizer"

In [32]:
batch_size = 4
input_features = 256
dummy_input = torch.randn(batch_size, input_features,)

#target = torch.empty(4, dtype=torch.float).random_(10)
target = torch.tensor([9., 5., 4., 4.], dtype=torch.long)

In [33]:
output = model("自行輸入")
print(output)

tensor([[0.0421, 0.0738, 0.1225, 0.1348, 0.0690, 0.1156, 0.0970, 0.0539, 0.1219,
         0.1693],
        [0.0542, 0.1019, 0.0638, 0.0874, 0.1024, 0.1207, 0.1127, 0.1087, 0.1327,
         0.1156],
        [0.0312, 0.1282, 0.0617, 0.1189, 0.1105, 0.1097, 0.1882, 0.0417, 0.1109,
         0.0990],
        [0.0554, 0.0540, 0.0639, 0.1007, 0.0511, 0.0920, 0.1304, 0.1811, 0.1500,
         0.1214]], grad_fn=<SoftmaxBackward>)


### 計算 CrossEntropy Loss
* 請注意哪一個 Loss最適合：我們已經使用 softmax
* 因為我們有使用dropout，並隨機產生dummy_input，所以各為學員得到的值會與解答不同，然而步驟原理需要相同

In [43]:
from torch.nn import NLLLoss, LogSoftmax, CrossEntropyLoss

In [44]:
criterion = "自行輸入"

In [45]:
loss = criterion(torch.log("自行輸入"), "自行輸入")

### 完成back propagation並更新梯度

In [37]:
"自行輸入"

In [38]:
print('weight : {}'.format(model.layer1.linear[0].weight))
print('\n')
print('grad : {}'.format(model.layer1.linear[0].weight.grad))

weight : Parameter containing:
tensor([[-0.0010, -0.0383, -0.0060,  ...,  0.0358, -0.0245, -0.0277],
        [-0.0432, -0.0382,  0.0384,  ...,  0.0360,  0.0118,  0.0447],
        [-0.0276, -0.0522, -0.0146,  ...,  0.0208,  0.0569,  0.0154],
        ...,
        [ 0.0122, -0.0478,  0.0501,  ..., -0.0181, -0.0309, -0.0114],
        [ 0.0263,  0.0399,  0.0579,  ..., -0.0354, -0.0192, -0.0358],
        [-0.0495, -0.0101,  0.0543,  ...,  0.0428,  0.0069,  0.0212]],
       requires_grad=True)


grad : tensor([[ 0.0834, -0.0256, -0.0764,  ...,  0.0718,  0.0144,  0.0422],
        [ 0.1144, -0.0429, -0.0292,  ..., -0.0337,  0.0184, -0.0535],
        [-0.2403,  0.1393,  0.2140,  ..., -0.1664, -0.1559, -0.0831],
        ...,
        [-0.2777,  0.1198,  0.1241,  ..., -0.1771,  0.0594, -0.0452],
        [-0.0297,  0.1155, -0.0428,  ...,  0.0807, -0.1282,  0.0959],
        [ 0.0055, -0.0410, -0.0648,  ...,  0.0877,  0.0826,  0.0698]])


In [39]:
"自行輸入"

In [40]:
print('weight : {}'.format(model.layer1.linear[0].weight))
print('\n')
print('grad : {}'.format(model.layer1.linear[0].weight.grad))

weight : Parameter containing:
tensor([[-0.0020, -0.0373, -0.0050,  ...,  0.0348, -0.0255, -0.0287],
        [-0.0442, -0.0372,  0.0394,  ...,  0.0370,  0.0108,  0.0457],
        [-0.0266, -0.0532, -0.0156,  ...,  0.0218,  0.0579,  0.0164],
        ...,
        [ 0.0132, -0.0488,  0.0491,  ..., -0.0171, -0.0319, -0.0104],
        [ 0.0273,  0.0389,  0.0589,  ..., -0.0364, -0.0182, -0.0368],
        [-0.0505, -0.0091,  0.0553,  ...,  0.0418,  0.0059,  0.0202]],
       requires_grad=True)


grad : tensor([[ 0.0834, -0.0256, -0.0764,  ...,  0.0718,  0.0144,  0.0422],
        [ 0.1144, -0.0429, -0.0292,  ..., -0.0337,  0.0184, -0.0535],
        [-0.2403,  0.1393,  0.2140,  ..., -0.1664, -0.1559, -0.0831],
        ...,
        [-0.2777,  0.1198,  0.1241,  ..., -0.1771,  0.0594, -0.0452],
        [-0.0297,  0.1155, -0.0428,  ...,  0.0807, -0.1282,  0.0959],
        [ 0.0055, -0.0410, -0.0648,  ...,  0.0877,  0.0826,  0.0698]])


### 清空 gradient

In [41]:
"自行輸入"

In [42]:
print('weight : {}'.format(model.layer1.linear[0].weight))
print('\n')
print('grad : {}'.format(model.layer1.linear[0].weight.grad))

weight : Parameter containing:
tensor([[-0.0020, -0.0373, -0.0050,  ...,  0.0348, -0.0255, -0.0287],
        [-0.0442, -0.0372,  0.0394,  ...,  0.0370,  0.0108,  0.0457],
        [-0.0266, -0.0532, -0.0156,  ...,  0.0218,  0.0579,  0.0164],
        ...,
        [ 0.0132, -0.0488,  0.0491,  ..., -0.0171, -0.0319, -0.0104],
        [ 0.0273,  0.0389,  0.0589,  ..., -0.0364, -0.0182, -0.0368],
        [-0.0505, -0.0091,  0.0553,  ...,  0.0418,  0.0059,  0.0202]],
       requires_grad=True)


grad : tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
