<a href="https://colab.research.google.com/github/jimmywang2/NLP/blob/main/homework/%E8%AA%8D%E8%AD%98%E5%BC%B5%E9%87%8F%E8%88%87%E5%85%B6%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [4]:
# Example 1 - ### your explanation ### 將torch tensor與numpy ndarray互相轉換
### your code ###
a = np.random.rand(1,2,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [5]:
# Example 2 - ### your explanation ### 經過轉換後，torch tensor與numpy array依然有相近的資料型態
### your code ###
a = np.random.randint(low=0, high=10, size=(2,1))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 2 - your function to illustrate

In [11]:
# Example 1 - ### your explanation ###
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
print(a.shape)

g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
print(g.shape)

h = torch.squeeze(g) #壓縮為度為1的位置
print(h.shape)

torch.Size([2, 2, 3])
torch.Size([2, 1, 2, 3])
torch.Size([2, 2, 3])


In [13]:
# Example 2 - ### your explanation ###
### your code ###
a = torch.randn((2,3))
print(a.shape)

g = torch.unsqueeze(a, dim=2) #增加維度在2的位置
print(g.shape)

h = torch.squeeze(g) #壓縮為度為2的位置
print(h.shape)


torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([2, 3])


### Function 3 - your function to illustrate

In [20]:
# Example 1 - ### your explanation ###
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
# 調換tensor維度
e = a.permute((0, 2, 1)) # permute 給定輸出的維度順序，如 (0,2,1) 代表輸出的維度順序是原本張量維度的 0,2,1 順序
f = a.transpose(1,2) # transpose 將給定維度進行對調，如 (1,2) 將原本的第 1 維與第 2 維進行對調
print(a.shape, e.shape, f.shape)
print(a, e, f)


torch.Size([2, 2, 3]) torch.Size([2, 3, 2]) torch.Size([2, 3, 2])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]]) tensor([[[1, 3],
         [2, 4],
         [3, 5]],

        [[5, 7],
         [6, 8],
         [7, 9]]]) tensor([[[1, 3],
         [2, 4],
         [3, 5]],

        [[5, 7],
         [6, 8],
         [7, 9]]])


In [21]:
# Example 2 - ### your explanation ###
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
# 調換tensor維度
e = a.permute((1, 0, 2)) # permute 給定輸出的維度順序, 1,0,2 順序
f = a.transpose(0,1) # transpose 將給定維度進行對調，如 (1,2) 將原本的第 0 維與第 1 維進行對調
print(a.shape, e.shape, f.shape)
print(a, e, f)

torch.Size([2, 2, 3]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]]) tensor([[[1, 2, 3],
         [5, 6, 7]],

        [[3, 4, 5],
         [7, 8, 9]]]) tensor([[[1, 2, 3],
         [5, 6, 7]],

        [[3, 4, 5],
         [7, 8, 9]]])


### Function 4 - your function to illustrate

In [23]:
# Example 1 - ### your explanation ### reshape 與 view 皆可以用來改變 tensor 的形狀
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)

# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(2, -1) #在給定的形狀中，我們可以給 -1，代表這個維度的元素是剩下的所有元素個數
print(b.shape, c.shape, d.shape)
print(b, c, d)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])
tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])


In [26]:
# Example 2 - ### your explanation ###
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)

# 將tensor形狀由[2,2,3]改為[4,3]
b = a.reshape(4, 3)
c = a.view(4, 3)
d = a.reshape(3, -1) #在給定的形狀中，我們可以給 -1，代表這個維度的元素是剩下的所有元素個數
print(b.shape, c.shape, d.shape)
print(b, c, d)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([4, 3]) torch.Size([4, 3]) torch.Size([3, 4])
tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]) tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]) tensor([[1, 2, 3, 3],
        [4, 5, 5, 6],
        [7, 7, 8, 9]])
